version: '3'

services:
  front-end:
    container_name: dirty-minded-ui
    environment:
      - REACT_APP_SOCKET_URL=websocket
      - REACT_APP_MAX_PLAYERS=3
      - REACT_APP_MIN_PLAYERS=2
      - REACT_APP_CARDS_PER_PLAYER=5
      - REACT_APP_INVITE_URL=http://localhost:3000?room=
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:80"