on: 
  push:
    branches:
    - main
    - develop
name: dirty-minded-workflow
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/${{ github.repository }}
        tags: v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        